### PR TITLE
Setup locales for extension

### PR DESCRIPTION
**Pull request by ganicke**
Create the locale setup for the extension.

I've patched in just one locale ``zh`` but this can be copied for the others (see [Extension localization](https://makecode.com/extensions/localization) for further details).

Review the function and parameter descriptions for accuracy as I'm not sure what's intended by the "L4, L5, L6" naming (levels I'm assuming).

Also, will need to verify that the ``zh`` code is sufficient or if ``zh-cn`` is needed to select the locale for that particular language.

### CODE REVIEW

**Comment by ganicke** [comment]
@abchatra , @MariaOlekheyko

**Comment by abchatra** [comment]
@ganicke  looks good to me. Good to merge? I have given write access to you as well. So feel free to merge.

**Comment by abchatra** [comment]
If you specify just zh, then both Chinese Traditional and Chinese Simplified will be mapped to the same locale. I am unsure if that is ok for the translator. Otherwise you need to specify specific locale. 
zh-CN
zh-TW

**Comment by ganicke** [comment]
OK, we can merge and extend the zh locales if necessary. I need to put together an email and see what all the parties are think as far as the HoC contributions goes. They wanted to upload markdown to an `en` folder but I pushed back saying that we'll go the Crowdin route with this content.

**Comment by ganicke** [comment]
Otherwise, it would be nice to put the docs in this extension and have a brief release cycle that auto-loads the extension and "plugs-in" the HoC docs.

**Pull request merged**
